# Generated by Django 4.0.3 on 2022-04-07 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doencas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sintomas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pesos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.PositiveSmallIntegerField(choices=[(1, 'Muito Raro'), (2, 'Raro'), (3, 'Pouco Comum'), (4, 'Comum'), (5, 'Muito Comum')])),
                ('doenca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigdoc.doencas')),
                ('sintoma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigdoc.sintomas')),
            ],
        ),
        migrations.AddField(
            model_name='doencas',
            name='sintomas',
            field=models.ManyToManyField(to='bigdoc.sintomas'),
        ),
    ]
