# Generated by Django 4.0.3 on 2022-04-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigdoc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('ordem', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Sintoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('ordem', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.RemoveField(
            model_name='pesos',
            name='doenca',
        ),
        migrations.RemoveField(
            model_name='pesos',
            name='sintoma',
        ),
        migrations.DeleteModel(
            name='Doencas',
        ),
        migrations.DeleteModel(
            name='Pesos',
        ),
        migrations.DeleteModel(
            name='Sintomas',
        ),
    ]
